### ISSUE TITLE
[Feature Request] Shortcut/Symbol to not replace timestamp

### ISSUE THREAD

**Issue by njharoon** [domi-btnr/BetterDiscordStuff#25]
### Discord Account

Supernaafeh#6638

### Describe the bug

Most of the time I do want it replaced but sometimes I don't. My current method is to put a \ before my time and edit it out but that is pretty inconvenient. I am hoping you can implement a way to not have a time be replaced.

### How can I recreate this bug

No bug, this is a feature request.

**Comment by lurts** [comment]
My workaround is to escape the : in the time. Like this: 6\:00. The slash doesn't show up in the message and it won't get converted. But having an option for a character that disables automatic conversion would be nice

**Comment by ItsEliot** [comment]
@lurts how are you getting this plugin to work 😭please reply back or DM me on discord at "itseliot"

**Comment by domi-btnr** [comment]
> @lurts how are you getting this plugin to work 😭please reply back or DM me on discord at "itseliot"

I fixed the Plugin in 2e52ebc

**Comment by domi-btnr** [comment]
> My workaround is to escape the : in the time. Like this: `6\:00`. The slash doesn't show up in the message and it won't get converted. But having an option for a character that disables automatic conversion would be nice

This seems to be the best solution.

Implementing a feature to selectively disable timestamp replacement without overcomplicating the plugin is challenging. Adding buttons or toggles would clutter the message bar, which goes against the goal of keeping the plugin simple and user-friendly.

Therefore, I will close this issue as the current workaround is the most practical solution available without introducing unnecessary complexity.
