### ISSUE TITLE
BetterInvites - Don't show changelog on every startup.

### ISSUE THREAD

**Issue by MagmaBro123** [domi-btnr/BetterDiscordStuff#33]
### Describe the bug

Title.

### How can I recreate this bug

Use the plugin. Start Discord.

**Comment by domi-btnr** [comment]
I fixed that in the recent update. The problem was that I switched from a JSON Object to the Flux Store but forgot to update the change log method. 

Please redownload the Plugin

**Comment by domi-btnr** [comment]
@MagmaBro123 Can I close the issue?

**Comment by MagmaBro123** [comment]
Sure.
